name: CMake

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CC: "gcc"
  CXX: "g++"

jobs:
  build_and_test_mingw:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Create folders
      run: |
          mkdir -p ${{github.workspace}}/install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DEXTERNAL_EIGEN:BOOL=OFF -DPYTHON_WRAPPER:BOOL=OFF -DFORTRAN_WRAPPER:BOOL=ON -DRUST_WRAPPER:BOOL=OFF -DUSE_VTK=OFF -DBUILD_TESTING=ON

    - name: Build
      id: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
